project_id = "phmqxmwaoonbibgvbumq"

[functions.generate-devis-proposal]
verify_jwt = true

[functions.analyze-meeting-report]
verify_jwt = true

[functions.parse-bank-statement-pdf]
verify_jwt = true

[functions.send-devis-proposal]
verify_jwt = true

[functions.manage-users]
verify_jwt = true

[functions.accept-devis-proposal]
verify_jwt = false

[functions.translate-devis]
verify_jwt = true
