/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOperacaoRouteImport } from './routes/_authenticated/operacao'
import { Route as AuthenticatedHubRouteImport } from './routes/_authenticated/hub'
import { Route as AuthenticatedGestaoRouteImport } from './routes/_authenticated/gestao'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedConciliacaoRouteImport } from './routes/_authenticated/conciliacao'
import { Route as AuthenticatedComercialRouteImport } from './routes/_authenticated/comercial'
import { Route as AuthenticatedBiRouteImport } from './routes/_authenticated/bi'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as PropostaAceiteTokenRouteImport } from './routes/proposta.aceite.$token'
import { Route as AuthenticatedAdminApiKeysRouteImport } from './routes/_authenticated/admin.api-keys'
import { Route as AuthenticatedComercialDevisIdRouteImport } from './routes/_authenticated/comercial_.devis.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOperacaoRoute = AuthenticatedOperacaoRouteImport.update({
  id: '/operacao',
  path: '/operacao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHubRoute = AuthenticatedHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGestaoRoute = AuthenticatedGestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConciliacaoRoute =
  AuthenticatedConciliacaoRouteImport.update({
    id: '/conciliacao',
    path: '/conciliacao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComercialRoute = AuthenticatedComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBiRoute = AuthenticatedBiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PropostaAceiteTokenRoute = PropostaAceiteTokenRouteImport.update({
  id: '/proposta/aceite/$token',
  path: '/proposta/aceite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminApiKeysRoute =
  AuthenticatedAdminApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedComercialDevisIdRoute =
  AuthenticatedComercialDevisIdRouteImport.update({
    id: '/comercial_/devis/$id',
    path: '/comercial/devis/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/bi': typeof AuthenticatedBiRoute
  '/comercial': typeof AuthenticatedComercialRoute
  '/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/gestao': typeof AuthenticatedGestaoRoute
  '/hub': typeof AuthenticatedHubRoute
  '/operacao': typeof AuthenticatedOperacaoRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/proposta/aceite/$token': typeof PropostaAceiteTokenRoute
  '/comercial/devis/$id': typeof AuthenticatedComercialDevisIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/bi': typeof AuthenticatedBiRoute
  '/comercial': typeof AuthenticatedComercialRoute
  '/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/gestao': typeof AuthenticatedGestaoRoute
  '/hub': typeof AuthenticatedHubRoute
  '/operacao': typeof AuthenticatedOperacaoRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/proposta/aceite/$token': typeof PropostaAceiteTokenRoute
  '/comercial/devis/$id': typeof AuthenticatedComercialDevisIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/bi': typeof AuthenticatedBiRoute
  '/_authenticated/comercial': typeof AuthenticatedComercialRoute
  '/_authenticated/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/gestao': typeof AuthenticatedGestaoRoute
  '/_authenticated/hub': typeof AuthenticatedHubRoute
  '/_authenticated/operacao': typeof AuthenticatedOperacaoRoute
  '/_authenticated/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/proposta/aceite/$token': typeof PropostaAceiteTokenRoute
  '/_authenticated/comercial_/devis/$id': typeof AuthenticatedComercialDevisIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/bi'
    | '/comercial'
    | '/conciliacao'
    | '/financeiro'
    | '/gestao'
    | '/hub'
    | '/operacao'
    | '/admin/api-keys'
    | '/proposta/aceite/$token'
    | '/comercial/devis/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/bi'
    | '/comercial'
    | '/conciliacao'
    | '/financeiro'
    | '/gestao'
    | '/hub'
    | '/operacao'
    | '/admin/api-keys'
    | '/proposta/aceite/$token'
    | '/comercial/devis/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/bi'
    | '/_authenticated/comercial'
    | '/_authenticated/conciliacao'
    | '/_authenticated/financeiro'
    | '/_authenticated/gestao'
    | '/_authenticated/hub'
    | '/_authenticated/operacao'
    | '/_authenticated/admin/api-keys'
    | '/proposta/aceite/$token'
    | '/_authenticated/comercial_/devis/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  PropostaAceiteTokenRoute: typeof PropostaAceiteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/operacao': {
      id: '/_authenticated/operacao'
      path: '/operacao'
      fullPath: '/operacao'
      preLoaderRoute: typeof AuthenticatedOperacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hub': {
      id: '/_authenticated/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof AuthenticatedHubRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gestao': {
      id: '/_authenticated/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof AuthenticatedGestaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conciliacao': {
      id: '/_authenticated/conciliacao'
      path: '/conciliacao'
      fullPath: '/conciliacao'
      preLoaderRoute: typeof AuthenticatedConciliacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comercial': {
      id: '/_authenticated/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof AuthenticatedComercialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bi': {
      id: '/_authenticated/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof AuthenticatedBiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/proposta/aceite/$token': {
      id: '/proposta/aceite/$token'
      path: '/proposta/aceite/$token'
      fullPath: '/proposta/aceite/$token'
      preLoaderRoute: typeof PropostaAceiteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/api-keys': {
      id: '/_authenticated/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AuthenticatedAdminApiKeysRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/comercial_/devis/$id': {
      id: '/_authenticated/comercial_/devis/$id'
      path: '/comercial/devis/$id'
      fullPath: '/comercial/devis/$id'
      preLoaderRoute: typeof AuthenticatedComercialDevisIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminApiKeysRoute: typeof AuthenticatedAdminApiKeysRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminApiKeysRoute: AuthenticatedAdminApiKeysRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBiRoute: typeof AuthenticatedBiRoute
  AuthenticatedComercialRoute: typeof AuthenticatedComercialRoute
  AuthenticatedConciliacaoRoute: typeof AuthenticatedConciliacaoRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedGestaoRoute: typeof AuthenticatedGestaoRoute
  AuthenticatedHubRoute: typeof AuthenticatedHubRoute
  AuthenticatedOperacaoRoute: typeof AuthenticatedOperacaoRoute
  AuthenticatedComercialDevisIdRoute: typeof AuthenticatedComercialDevisIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBiRoute: AuthenticatedBiRoute,
  AuthenticatedComercialRoute: AuthenticatedComercialRoute,
  AuthenticatedConciliacaoRoute: AuthenticatedConciliacaoRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedGestaoRoute: AuthenticatedGestaoRoute,
  AuthenticatedHubRoute: AuthenticatedHubRoute,
  AuthenticatedOperacaoRoute: AuthenticatedOperacaoRoute,
  AuthenticatedComercialDevisIdRoute: AuthenticatedComercialDevisIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  PropostaAceiteTokenRoute: PropostaAceiteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
